variable "package_file_name" {
    type        = string
    default     = "lambda.zip"
    description = "Package file name generated by github actions"
}

variable "function_name" {
    type        = string
    default     = "lambda_test"
}