name: custome_action

on:
  # push:
  #   branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      OPERATE:
        description: "Choose operation"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

env:
  AWS_REGION: ap-northeast-1
  JOB_NAME: custome_action # Same as job name
  STORE_PATH: state/${{ github.event.repository.name }}/custome_action
  TERRAFORM_WORK_DIR: src/custome_action

permissions:
  id-token: write
  contents: read

jobs:
  check:
    if: github.event_name == 'workflow_dispatch'
    name: check credentials
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: 'arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_VPC_ACCESS_ROLE }}'


  deploy:
    if: github.event_name == 'workflow_dispatch'
    name: deploy resource test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: 'arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_VPC_ACCESS_ROLE }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Get state file
        uses: ./_action/_tfstate_pull_module.yaml

      - name: Deploy process apply/destrot
        uses: ./_action/_terraform_${{ inputs.OPERATE }}_module.yaml

      - name: Upload state file
        uses: ./_action/_tfstate_push_module.yaml