name: custome_action

on:
  # push:
  #   branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      OPERATE:
        description: "Choose operation"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

env:
  AWS_REGION: ap-northeast-1
  JOB_NAME: custom_action # Same as job name
  STORE_PATH: state/${{ github.event.repository.name }}/custom_action
  TERRAFORM_WORK_DIR: src/custom_action

permissions:
  id-token: write
  contents: read

jobs:
  check:
    if: github.event_name == 'workflow_dispatch'
    name: check credentials
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: 'arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_VPC_ACCESS_ROLE }}'


  deploy:
    if: github.event_name == 'workflow_dispatch'
    name: deploy resource test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: 'arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_VPC_ACCESS_ROLE }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Get state file
        uses: ./.github/actions/_tfstate_pull_module/
        with:
          state_repo_name: ${{ secrets.STATE_REPO_NAME }}
          state_repo_token: ${{ secrets.STATE_REPO_TOKEN }}
          store_path: ${{ env.STORE_PATH }}
          terraform_work_path: ${{ env.TERRAFORM_WORK_DIR}}

      - name: Deploy process apply
        if: ${{ github.event.inputs.OPERATE == 'apply' }}
        uses: ./.github/actions/_terraform_apply_module/
        with:
          terraform_work_path: ${{ env.TERRAFORM_WORK_DIR}}

      - name: Deploy process destroy
        if: ${{ github.event.inputs.OPERATE == 'destroy' }}
        uses: ./.github/actions/_terraform_destroy_module/
        with:
          terraform_work_path: ${{ env.TERRAFORM_WORK_DIR}}

      - name: Upload state file
        uses: ./.github/actions/_tfstate_push_module/
        with:
          state_repo_name: ${{ secrets.STATE_REPO_NAME }}
          state_repo_token: ${{ secrets.STATE_REPO_TOKEN }}
          store_path: ${{ env.STORE_PATH }}
          terraform_work_path: ${{ env.TERRAFORM_WORK_DIR}}