name: init

on:
  # push:
  #   branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-1


jobs:
  delivery:
    name: aws-cd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_CICD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CICD_SECRET_ACCESS_KEY }}
          aws-regiom: ${{ env.AWS_REGION }}

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_CICD_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Generate inventory
        run: |
          cat <<EOF > ansible/inventory.ini
          [web]
          ${{ secrets.EC2_CICD_HOST }} ansible_user=${{ secrets.EC2_CICD_USER }} ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_python_interpreter=/usr/bin/python3
          EOF

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible